### ISSUE TITLE
Define versions of images in env vars

### ISSUE THREAD

**Issue by maehr** [open-museum/open-museum.ch#4]
**Is your feature request related to a problem? Please describe.**
At the moment every new version needs an update in the codebase.

**Describe the solution you'd like**
Make the following changes to https://github.com/open-museum/open-museum.ch/blob/master/docker-compose.yml

```yml
  web:
    image: openmuseum/web:${WEB_VERSION}
    restart: unless-stopped
    labels:
      - traefik.http.routers.web.rule=Host(`open-museum.ch`)
      - traefik.http.routers.web.tls=true
      - traefik.http.routers.web.tls.certresolver=dns-cloudflare
```

and fix https://github.com/open-museum/open-museum.ch/blob/master/example.env accordingly.

**Describe alternatives you've considered**
Keep it as it is.

**Additional context**
I have not tested this solution
